
SET IDENTITY_INSERT [dbo].[Cities] ON 

INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (1, N'ADANA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (2, N'ADIYAMAN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (3, N'AFYON', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (4, N'AĞRI', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (5, N'AMASYA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (6, N'ANKARA', 2)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (7, N'ANTALYA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (8, N'ARTVİN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (9, N'AYDIN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (10, N'BALIKESİR', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (11, N'BİLECİK', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (12, N'BİNGÖL', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (13, N'BİTLİS', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (14, N'BOLU', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (15, N'BURDUR', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (16, N'BURSA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (17, N'ÇANAKKALE', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (18, N'ÇANKIRI', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (19, N'ÇORUM', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (20, N'DENİZLİ', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (21, N'DİYARBAKIR', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (22, N'EDİRNE', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (23, N'ELAZIĞ', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (24, N'ERZİNCAN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (25, N'ERZURUM', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (26, N'ESKİŞEHİR', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (27, N'GAZİANTEP', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (28, N'GİRESUN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (29, N'GÜMÜŞHANE', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (30, N'HAKKARİ', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (31, N'HATAY', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (32, N'ISPARTA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (33, N'İÇEL', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (34, N'İSTANBUL', 1)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (35, N'İZMİR', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (36, N'KARS', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (37, N'KASTAMONU', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (38, N'KAYSERİ', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (39, N'KIRKLARELİ', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (40, N'KIRŞEHİR', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (41, N'KOCAELİ', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (42, N'KONYA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (43, N'KÜTAHYA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (44, N'MALATYA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (45, N'MANİSA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (46, N'KAHRAMANMARAŞ', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (47, N'MARDİN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (48, N'MUĞLA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (49, N'MUŞ', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (50, N'NEVŞEHİR', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (51, N'NİĞDE', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (52, N'ORDU', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (53, N'RİZE', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (54, N'SAKARYA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (55, N'SAMSUN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (56, N'SİİRT', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (57, N'SİNOP', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (58, N'SİVAS', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (59, N'TEKİRDAĞ', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (60, N'TOKAT', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (61, N'TRABZON', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (62, N'TUNCELİ', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (63, N'ŞANLIURFA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (64, N'UŞAK', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (65, N'VAN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (66, N'YOZGAT', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (67, N'ZONGULDAK', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (68, N'AKSARAY', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (69, N'BAYBURT', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (70, N'KARAMAN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (71, N'KIRIKKALE', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (72, N'BATMAN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (73, N'ŞIRNAK', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (74, N'BARTIN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (75, N'ARDAHAN', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (76, N'IĞDIR', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (77, N'YALOVA', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (78, N'KARABÜK', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (79, N'KİLİS', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (80, N'OSMANİYE', 3)
INSERT [dbo].[Cities] ([Id], [Name], [Order]) VALUES (81, N'DÜZCE', 3)
SET IDENTITY_INSERT [dbo].[Cities] OFF
SET IDENTITY_INSERT [dbo].[States] ON 

INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (1, N'SEYHAN', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (2, N'CEYHAN', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (3, N'FEKE', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (4, N'KARAISALI', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (5, N'KARATAS', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (6, N'KOZAN', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (7, N'POZANTI', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (8, N'SAIMBEYLI', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (9, N'TUFANBEYLI', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (10, N'YUMURTALIK', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (11, N'YÜREGIR', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (12, N'ALADAG', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (13, N'IMAMOGLU', 1)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (14, N'ADIYAMAN MERKEZ', 2)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (15, N'BESNI', 2)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (16, N'ÇELIKHAN', 2)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (17, N'GERGER', 2)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (18, N'GÖLBASI', 2)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (19, N'KAHTA', 2)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (20, N'SAMSAT', 2)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (21, N'SINCIK', 2)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (22, N'TUT', 2)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (23, N'AFYONMERKEZ', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (24, N'BOLVADIN', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (25, N'ÇAY', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (26, N'DAZKIRI', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (27, N'DINAR', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (28, N'EMIRDAG', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (29, N'IHSANIYE', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (30, N'SANDIKLI', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (31, N'SINANPASA', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (32, N'SULDANDAGI', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (33, N'SUHUT', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (34, N'BASMAKÇI', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (35, N'BAYAT', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (36, N'ISCEHISAR', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (37, N'ÇOBANLAR', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (38, N'EVCILER', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (39, N'HOCALAR', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (40, N'KIZILÖREN', 3)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (41, N'AKSARAY MERKEZ', 68)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (42, N'ORTAKÖY', 68)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (43, N'AGAÇÖREN', 68)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (44, N'GÜZELYURT', 68)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (45, N'SARIYAHSI', 68)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (46, N'ESKIL', 68)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (47, N'GÜLAGAÇ', 68)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (48, N'AMASYA MERKEZ', 5)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (49, N'GÖYNÜÇEK', 5)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (50, N'GÜMÜSHACIKÖYÜ', 5)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (51, N'MERZIFON', 5)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (52, N'SULUOVA', 5)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (53, N'TASOVA', 5)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (54, N'HAMAMÖZÜ', 5)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (55, N'ALTINDAG', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (56, N'AYAS', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (57, N'BALA', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (58, N'BEYPAZARI', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (59, N'ÇAMLIDERE', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (60, N'ÇANKAYA', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (61, N'ÇUBUK', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (62, N'ELMADAG', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (63, N'GÜDÜL', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (64, N'HAYMANA', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (65, N'KALECIK', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (66, N'KIZILCAHAMAM', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (67, N'NALLIHAN', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (68, N'POLATLI', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (69, N'SEREFLIKOÇHISAR', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (70, N'YENIMAHALLE', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (71, N'GÖLBASI', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (72, N'KEÇIÖREN', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (73, N'MAMAK', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (74, N'SINCAN', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (75, N'KAZAN', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (76, N'AKYURT', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (77, N'ETIMESGUT', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (78, N'EVREN', 6)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (79, N'ANSEKI', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (80, N'ALANYA', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (81, N'ANTALYA MERKEZI', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (82, N'ELMALI', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (83, N'FINIKE', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (84, N'GAZIPASA', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (85, N'GÜNDOGMUS', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (86, N'KAS', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (87, N'KORKUTELI', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (88, N'KUMLUCA', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (89, N'MANAVGAT', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (90, N'SERIK', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (91, N'DEMRE', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (92, N'IBRADI', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (93, N'KEMER', 7)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (94, N'ARDAHAN MERKEZ', 75)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (95, N'GÖLE', 75)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (96, N'ÇILDIR', 75)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (97, N'HANAK', 75)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (98, N'POSOF', 75)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (99, N'DAMAL', 75)
GO
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (100, N'ARDANUÇ', 8)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (101, N'ARHAVI', 8)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (102, N'ARTVIN MERKEZ', 8)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (103, N'BORÇKA', 8)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (104, N'HOPA', 8)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (105, N'SAVSAT', 8)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (106, N'YUSUFELI', 8)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (107, N'MURGUL', 8)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (108, N'AYDIN MERKEZ', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (109, N'BOZDOGAN', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (110, N'ÇINE', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (111, N'GERMENCIK', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (112, N'KARACASU', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (113, N'KOÇARLI', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (114, N'KUSADASI', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (115, N'KUYUCAK', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (116, N'NAZILLI', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (117, N'SÖKE', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (118, N'SULTANHISAR', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (119, N'YENIPAZAR', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (120, N'BUHARKENT', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (121, N'INCIRLIOVA', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (122, N'KARPUZLU', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (123, N'KÖSK', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (124, N'DIDIM', 9)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (125, N'AGRI MERKEZ', 4)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (126, N'DIYADIN', 4)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (127, N'DOGUBEYAZIT', 4)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (128, N'ELESKIRT', 4)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (129, N'HAMUR', 4)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (130, N'PATNOS', 4)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (131, N'TASLIÇAY', 4)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (132, N'TUTAK', 4)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (133, N'AYVALIK', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (134, N'BALIKESIR MERKEZ', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (135, N'BALYA', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (136, N'BANDIRMA', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (137, N'BIGADIÇ', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (138, N'BURHANIYE', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (139, N'DURSUNBEY', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (140, N'EDREMIT', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (141, N'ERDEK', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (142, N'GÖNEN', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (143, N'HAVRAN', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (144, N'IVRINDI', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (145, N'KEPSUT', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (146, N'MANYAS', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (147, N'SAVASTEPE', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (148, N'SINDIRGI', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (149, N'SUSURLUK', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (150, N'MARMARA', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (151, N'GÖMEÇ', 10)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (152, N'BARTIN MERKEZ', 74)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (153, N'KURUCASILE', 74)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (154, N'ULUS', 74)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (155, N'AMASRA', 74)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (156, N'BATMAN MERKEZ', 72)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (157, N'BESIRI', 72)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (158, N'GERCÜS', 72)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (159, N'KOZLUK', 72)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (160, N'SASON', 72)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (161, N'HASANKEYF', 72)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (162, N'BAYBURT MERKEZ', 69)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (163, N'AYDINTEPE', 69)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (164, N'DEMIRÖZÜ', 69)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (165, N'BOLU MERKEZ', 14)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (166, N'GEREDE', 14)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (167, N'GÖYNÜK', 14)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (168, N'KIBRISCIK', 14)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (169, N'MENGEN', 14)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (170, N'MUDURNU', 14)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (171, N'SEBEN', 14)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (172, N'DÖRTDIVAN', 14)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (173, N'YENIÇAGA', 14)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (174, N'AGLASUN', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (175, N'BUCAK', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (176, N'BURDUR MERKEZ', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (177, N'GÖLHISAR', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (178, N'TEFENNI', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (179, N'YESILOVA', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (180, N'KARAMANLI', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (181, N'KEMER', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (182, N'ALTINYAYLA', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (183, N'ÇAVDIR', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (184, N'ÇELTIKÇI', 15)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (185, N'GEMLIK', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (186, N'INEGÖL', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (187, N'IZNIK', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (188, N'KARACABEY', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (189, N'KELES', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (190, N'MUDANYA', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (191, N'MUSTAFA K. PASA', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (192, N'ORHANELI', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (193, N'ORHANGAZI', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (194, N'YENISEHIR', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (195, N'BÜYÜK ORHAN', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (196, N'HARMANCIK', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (197, N'NÜLIFER', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (198, N'OSMAN GAZI', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (199, N'YILDIRIM', 16)
GO
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (200, N'GÜRSU', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (201, N'KESTEL', 16)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (202, N'BILECIK MERKEZ', 11)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (203, N'BOZÜYÜK', 11)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (204, N'GÖLPAZARI', 11)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (205, N'OSMANELI', 11)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (206, N'PAZARYERI', 11)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (207, N'SÖGÜT', 11)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (208, N'YENIPAZAR', 11)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (209, N'INHISAR', 11)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (210, N'BINGÖL MERKEZ', 12)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (211, N'GENÇ', 12)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (212, N'KARLIOVA', 12)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (213, N'KIGI', 12)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (214, N'SOLHAN', 12)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (215, N'ADAKLI', 12)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (216, N'YAYLADERE', 12)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (217, N'YEDISU', 12)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (218, N'ADILCEVAZ', 13)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (219, N'AHLAT', 13)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (220, N'BITLIS MERKEZ', 13)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (221, N'HIZAN', 13)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (222, N'MUTKI', 13)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (223, N'TATVAN', 13)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (224, N'GÜROYMAK', 13)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (225, N'DENIZLI MERKEZ', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (226, N'ACIPAYAM', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (227, N'BULDAN', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (228, N'ÇAL', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (229, N'ÇAMELI', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (230, N'ÇARDAK', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (231, N'ÇIVRIL', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (232, N'GÜNEY', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (233, N'KALE', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (234, N'SARAYKÖY', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (235, N'TAVAS', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (236, N'BABADAG', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (237, N'BEKILLI', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (238, N'HONAZ', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (239, N'SERINHISAR', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (240, N'AKKÖY', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (241, N'BAKLAN', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (242, N'BEYAGAÇ', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (243, N'BOZKURT', 20)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (244, N'DÜZCE MERKEZ', 81)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (245, N'AKÇAKOCA', 81)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (246, N'YIGILCA', 81)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (247, N'CUMAYERI', 81)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (248, N'GÖLYAKA', 81)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (249, N'ÇILIMLI', 81)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (250, N'GÜMÜSOVA', 81)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (251, N'KAYNASLI', 81)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (252, N'DIYARBAKIR MERKEZ', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (253, N'BISMIL', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (254, N'ÇERMIK', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (255, N'ÇINAR', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (256, N'ÇÜNGÜS', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (257, N'DICLE', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (258, N'ERGANI', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (259, N'HANI', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (260, N'HAZRO', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (261, N'KULP', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (262, N'LICE', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (263, N'SILVAN', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (264, N'EGIL', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (265, N'KOCAKÖY', 21)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (266, N'EDIRNE MERKEZ', 22)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (267, N'ENEZ', 22)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (268, N'HAVSA', 22)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (269, N'IPSALA', 22)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (270, N'KESAN', 22)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (271, N'LALAPASA', 22)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (272, N'MERIÇ', 22)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (273, N'UZUNKÖPRÜ', 22)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (274, N'SÜLOGLU', 22)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (275, N'ELAZIG MERKEZ', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (276, N'AGIN', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (277, N'BASKIL', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (278, N'KARAKOÇAN', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (279, N'KEBAN', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (280, N'MADEN', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (281, N'PALU', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (282, N'SIVRICE', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (283, N'ARICAK', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (284, N'KOVANCILAR', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (285, N'ALACAKAYA', 23)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (286, N'ERZURUM MERKEZ', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (287, N'PALANDÖKEN', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (288, N'ASKALE', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (289, N'ÇAT', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (290, N'HINIS', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (291, N'HORASAN', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (292, N'OLTU', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (293, N'ISPIR', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (294, N'KARAYAZI', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (295, N'NARMAN', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (296, N'OLUR', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (297, N'PASINLER', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (298, N'SENKAYA', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (299, N'TEKMAN', 25)
GO
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (300, N'TORTUM', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (301, N'KARAÇOBAN', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (302, N'UZUNDERE', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (303, N'PAZARYOLU', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (304, N'ILICA', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (305, N'KÖPRÜKÖY', 25)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (306, N'ÇAYIRLI', 24)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (307, N'ERZINCAN MERKEZ', 24)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (308, N'ILIÇ', 24)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (309, N'KEMAH', 24)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (310, N'KEMALIYE', 24)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (311, N'REFAHIYE', 24)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (312, N'TERCAN', 24)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (313, N'OTLUKBELI', 24)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (314, N'ESKISEHIR MERKEZ', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (315, N'ÇIFTELER', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (316, N'MAHMUDIYE', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (317, N'MIHALIÇLIK', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (318, N'SARICAKAYA', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (319, N'SEYITGAZI', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (320, N'SIVRIHISAR', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (321, N'ALPU', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (322, N'BEYLIKOVA', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (323, N'INÖNÜ', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (324, N'GÜNYÜZÜ', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (325, N'HAN', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (326, N'MIHALGAZI', 26)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (327, N'ARABAN', 27)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (328, N'ISLAHIYE', 27)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (329, N'NIZIP', 27)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (330, N'OGUZELI', 27)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (331, N'YAVUZELI', 27)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (332, N'SAHINBEY', 27)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (333, N'SEHIT KAMIL', 27)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (334, N'KARKAMIS', 27)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (335, N'NURDAGI', 27)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (336, N'GÜMÜSHANE MERKEZ', 29)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (337, N'KELKIT', 29)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (338, N'SIRAN', 29)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (339, N'TORUL', 29)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (340, N'KÖSE', 29)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (341, N'KÜRTÜN', 29)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (342, N'ALUCRA', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (343, N'BULANCAK', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (344, N'DERELI', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (345, N'ESPIYE', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (346, N'EYNESIL', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (347, N'GIRESUN MERKEZ', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (348, N'GÖRELE', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (349, N'KESAP', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (350, N'SEBINKARAHISAR', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (351, N'TIREBOLU', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (352, N'PIPAZIZ', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (353, N'YAGLIDERE', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (354, N'ÇAMOLUK', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (355, N'ÇANAKÇI', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (356, N'DOGANKENT', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (357, N'GÜCE', 28)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (358, N'HAKKARI MERKEZ', 30)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (359, N'ÇUKURCA', 30)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (360, N'SEMDINLI', 30)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (361, N'YÜKSEKOVA', 30)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (362, N'ALTINÖZÜ', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (363, N'DÖRTYOL', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (364, N'HATAY MERKEZ', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (365, N'HASSA', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (366, N'ISKENDERUN', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (367, N'KIRIKHAN', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (368, N'REYHANLI', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (369, N'SAMANDAG', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (370, N'YAYLADAG', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (371, N'ERZIN', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (372, N'BELEN', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (373, N'KUMLU', 31)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (374, N'ISPARTA MERKEZ', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (375, N'ATABEY', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (376, N'KEÇIBORLU', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (377, N'EGIRDIR', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (378, N'GELENDOST', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (379, N'SINIRKENT', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (380, N'ULUBORLU', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (381, N'YALVAÇ', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (382, N'AKSU', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (383, N'GÖNEN', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (384, N'YENISAR BADEMLI', 32)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (385, N'IGDIR MERKEZ', 76)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (386, N'ARALIK', 76)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (387, N'TUZLUCA', 76)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (388, N'KARAKOYUNLU', 76)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (389, N'AFSIN', 46)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (390, N'ANDIRIN', 46)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (391, N'ELBISTAN', 46)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (392, N'GÖKSUN', 46)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (393, N'KAHRAMANMARAS MERKEZ', 46)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (394, N'PAZARCIK', 46)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (395, N'TÜRKOGLU', 46)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (396, N'ÇAGLAYANCERIT', 46)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (397, N'EKINÖZÜ', 46)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (398, N'NURHAK', 46)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (399, N'EFLANI', 78)
GO
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (400, N'ESKIPAZAR', 78)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (401, N'KARABÜK MERKEZ', 78)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (402, N'OVACIK', 78)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (403, N'SAFRANBOLU', 78)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (404, N'YENICE', 78)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (405, N'ERMENEK', 70)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (406, N'KARAMAN MERKEZ', 70)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (407, N'AYRANCI', 70)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (408, N'KAZIMKARABEKIR', 70)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (409, N'BASYAYLA', 70)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (410, N'SARIVELILER', 70)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (411, N'KARS MERKEZ', 36)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (412, N'ARPAÇAY', 36)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (413, N'DIGOR', 36)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (414, N'KAGIZMAN', 36)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (415, N'SARIKAMIS', 36)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (416, N'SELIM', 36)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (417, N'SUSUZ', 36)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (418, N'AKYAKA', 36)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (419, N'ABANA', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (420, N'KASTAMONU MERKEZ', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (421, N'ARAÇ', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (422, N'AZDAVAY', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (423, N'BOZKURT', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (424, N'CIDE', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (425, N'ÇATALZEYTIN', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (426, N'DADAY', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (427, N'DEVREKANI', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (428, N'INEBOLU', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (429, N'KÜRE', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (430, N'TASKÖPRÜ', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (431, N'TOSYA', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (432, N'IHSANGAZI', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (433, N'PINARBASI', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (434, N'SENPAZAR', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (435, N'AGLI', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (436, N'DOGANYURT', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (437, N'HANÖNÜ', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (438, N'SEYDILER', 37)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (439, N'BÜNYAN', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (440, N'DEVELI', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (441, N'FELAHIYE', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (442, N'INCESU', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (443, N'PINARBASI', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (444, N'SARIOGLAN', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (445, N'SARIZ', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (446, N'TOMARZA', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (447, N'YAHYALI', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (448, N'YESILHISAR', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (449, N'AKKISLA', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (450, N'TALAS', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (451, N'KOCASINAN', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (452, N'MELIKGAZI', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (453, N'HACILAR', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (454, N'ÖZVATAN', 38)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (455, N'DERICE', 71)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (456, N'KESKIN', 71)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (457, N'KIRIKKALE MERKEZ', 71)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (458, N'SALAK YURT', 71)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (459, N'BAHSILI', 71)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (460, N'BALISEYH', 71)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (461, N'ÇELEBI', 71)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (462, N'KARAKEÇILI', 71)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (463, N'YAHSIHAN', 71)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (464, N'KIRKKLARELI MERKEZ', 39)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (465, N'BABAESKI', 39)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (466, N'DEMIRKÖY', 39)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (467, N'KOFÇAY', 39)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (468, N'LÜLEBURGAZ', 39)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (469, N'VIZE', 39)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (470, N'KIRSEHIR MERKEZ', 40)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (471, N'ÇIÇEKDAGI', 40)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (472, N'KAMAN', 40)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (473, N'MUCUR', 40)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (474, N'AKPINAR', 40)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (475, N'AKÇAKENT', 40)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (476, N'BOZTEPE', 40)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (477, N'KOCAELI MERKEZ', 41)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (478, N'GEBZE', 41)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (479, N'GÖLCÜK', 41)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (480, N'KANDIRA', 41)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (481, N'KARAMÜRSEL', 41)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (482, N'KÖRFEZ', 41)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (483, N'DERINCE', 41)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (484, N'KONYA MERKEZ', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (485, N'AKSEHIR', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (486, N'BEYSEHIR', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (487, N'BOZKIR', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (488, N'CIHANBEYLI', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (489, N'ÇUMRA', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (490, N'DOGANHISAR', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (491, N'EREGLI', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (492, N'HADIM', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (493, N'ILGIN', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (494, N'KADINHANI', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (495, N'KARAPINAR', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (496, N'KULU', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (497, N'SARAYÖNÜ', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (498, N'SEYDISEHIR', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (499, N'YUNAK', 42)
GO
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (500, N'AKÖREN', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (501, N'ALTINEKIN', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (502, N'DEREBUCAK', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (503, N'HÜYÜK', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (504, N'KARATAY', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (505, N'MERAM', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (506, N'SELÇUKLU', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (507, N'TASKENT', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (508, N'AHIRLI', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (509, N'ÇELTIK', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (510, N'DERBENT', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (511, N'EMIRGAZI', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (512, N'GÜNEYSINIR', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (513, N'HALKAPINAR', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (514, N'TUZLUKÇU', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (515, N'YALIHÜYÜK', 42)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (516, N'KÜTAHYA  MERKEZ', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (517, N'ALTINTAS', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (518, N'DOMANIÇ', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (519, N'EMET', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (520, N'GEDIZ', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (521, N'SIMAV', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (522, N'TAVSANLI', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (523, N'ASLANAPA', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (524, N'DUMLUPINAR', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (525, N'HISARCIK', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (526, N'SAPHANE', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (527, N'ÇAVDARHISAR', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (528, N'PAZARLAR', 43)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (529, N'KILIS MERKEZ', 79)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (530, N'ELBEYLI', 79)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (531, N'MUSABEYLI', 79)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (532, N'POLATELI', 79)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (533, N'MALATYA MERKEZ', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (534, N'AKÇADAG', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (535, N'ARAPGIR', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (536, N'ARGUVAN', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (537, N'DARENDE', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (538, N'DOGANSEHIR', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (539, N'HEKIMHAN', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (540, N'PÜTÜRGE', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (541, N'YESILYURT', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (542, N'BATTALGAZI', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (543, N'DOGANYOL', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (544, N'KALE', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (545, N'KULUNCAK', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (546, N'YAZIHAN', 44)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (547, N'AKHISAR', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (548, N'ALASEHIR', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (549, N'DEMIRCI', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (550, N'GÖRDES', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (551, N'KIRKAGAÇ', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (552, N'KULA', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (553, N'MANISA MERKEZ', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (554, N'SALIHLI', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (555, N'SARIGÖL', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (556, N'SARUHANLI', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (557, N'SELENDI', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (558, N'SOMA', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (559, N'TURGUTLU', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (560, N'AHMETLI', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (561, N'GÖLMARMARA', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (562, N'KÖPRÜBASI', 45)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (563, N'DERIK', 47)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (564, N'KIZILTEPE', 47)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (565, N'MARDIN MERKEZ', 47)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (566, N'MAZIDAGI', 47)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (567, N'MIDYAT', 47)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (568, N'NUSAYBIN', 47)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (569, N'ÖMERLI', 47)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (570, N'SAVUR', 47)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (571, N'YESILLI', 47)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (572, N'MERSIN MERKEZ', 33)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (573, N'ANAMUR', 33)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (574, N'ERDEMLI', 33)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (575, N'GÜLNAR', 33)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (576, N'MUT', 33)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (577, N'SILIFKE', 33)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (578, N'TARSUS', 33)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (579, N'AYDINCIK', 33)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (580, N'BOZYAZI', 33)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (581, N'ÇAMLIYAYLA', 33)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (582, N'BODRUM', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (583, N'DATÇA', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (584, N'FETHIYE', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (585, N'KÖYCEGIZ', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (586, N'MARMARIS', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (587, N'MILAS', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (588, N'MUGLA MERKEZ', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (589, N'ULA', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (590, N'YATAGAN', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (591, N'DALAMAN', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (592, N'KAVAKLI DERE', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (593, N'ORTACA', 48)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (594, N'BULANIK', 49)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (595, N'MALAZGIRT', 49)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (596, N'MUS MERKEZ', 49)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (597, N'VARTO', 49)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (598, N'HASKÖY', 49)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (599, N'KORKUT', 49)
GO
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (600, N'NEVSEHIR MERKEZ', 50)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (601, N'AVANOS', 50)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (602, N'DERINKUYU', 50)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (603, N'GÜLSEHIR', 50)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (604, N'HACIBEKTAS', 50)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (605, N'KOZAKLI', 50)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (606, N'ÜRGÜP', 50)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (607, N'ACIGÖL', 50)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (608, N'NIGDE MERKEZ', 51)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (609, N'BOR', 51)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (610, N'ÇAMARDI', 51)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (611, N'ULUKISLA', 51)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (612, N'ALTUNHISAR', 51)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (613, N'ÇIFTLIK', 51)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (614, N'AKKUS', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (615, N'AYBASTI', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (616, N'FATSA', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (617, N'GÖLKÖY', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (618, N'KORGAN', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (619, N'KUMRU', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (620, N'MESUDIYE', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (621, N'ORDU MERKEZ', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (622, N'PERSEMBE', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (623, N'ULUBEY', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (624, N'ÜNYE', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (625, N'GÜLYALI', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (626, N'GÜRGENTEPE', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (627, N'ÇAMAS', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (628, N'ÇATALPINAR', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (629, N'ÇAYBASI', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (630, N'IKIZCE', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (631, N'KABADÜZ', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (632, N'KABATAS', 52)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (633, N'BAHÇE', 80)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (634, N'KADIRLI', 80)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (635, N'OSMANIYE MERKEZ', 80)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (636, N'DÜZIÇI', 80)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (637, N'HASANBEYLI', 80)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (638, N'SUMBAS', 80)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (639, N'TOPRAKKALE', 80)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (640, N'RIZE MERKEZ', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (641, N'ARDESEN', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (642, N'ÇAMLIHEMSIN', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (643, N'ÇAYELI', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (644, N'FINDIKLI', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (645, N'IKIZDERE', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (646, N'KALKANDERE', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (647, N'PAZAR', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (648, N'GÜNEYSU', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (649, N'DEREPAZARI', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (650, N'HEMSIN', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (651, N'IYIDERE', 53)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (652, N'AKYAZI', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (653, N'GEYVE', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (654, N'HENDEK', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (655, N'KARASU', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (656, N'KAYNARCA', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (657, N'SAKARYA MERKEZ', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (658, N'PAMUKOVA', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (659, N'TARAKLI', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (660, N'FERIZLI', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (661, N'KARAPÜRÇEK', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (662, N'SÖGÜTLÜ', 54)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (663, N'ALAÇAM', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (664, N'BAFRA', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (665, N'ÇARSAMBA', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (666, N'HAVZA', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (667, N'KAVAK', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (668, N'LADIK', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (669, N'SAMSUN MERKEZ', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (670, N'TERME', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (671, N'VEZIRKÖPRÜ', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (672, N'ASARCIK', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (673, N'ONDOKUZMAYIS', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (674, N'SALIPAZARI', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (675, N'TEKKEKÖY', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (676, N'AYVACIK', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (677, N'YAKAKENT', 55)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (678, N'AYANCIK', 57)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (679, N'BOYABAT', 57)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (680, N'SINOP MERKEZ', 57)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (681, N'DURAGAN', 57)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (682, N'ERGELEK', 57)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (683, N'GERZE', 57)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (684, N'TÜRKELI', 57)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (685, N'DIKMEN', 57)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (686, N'SARAYDÜZÜ', 57)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (687, N'DIVRIGI', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (688, N'GEMEREK', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (689, N'GÜRÜN', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (690, N'HAFIK', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (691, N'IMRANLI', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (692, N'KANGAL', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (693, N'KOYUL HISAR', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (694, N'SIVAS MERKEZ', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (695, N'SU SEHRI', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (696, N'SARKISLA', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (697, N'YILDIZELI', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (698, N'ZARA', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (699, N'AKINCILAR', 58)
GO
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (700, N'ALTINYAYLA', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (701, N'DOGANSAR', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (702, N'GÜLOVA', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (703, N'ULAS', 58)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (704, N'BAYKAN', 56)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (705, N'ERUH', 56)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (706, N'KURTALAN', 56)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (707, N'PERVARI', 56)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (708, N'SIIRT MERKEZ', 56)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (709, N'SIRVARI', 56)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (710, N'AYDINLAR', 56)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (711, N'TEKIRDAG MERKEZ', 59)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (712, N'ÇERKEZKÖY', 59)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (713, N'ÇORLU', 59)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (714, N'HAYRABOLU', 59)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (715, N'MALKARA', 59)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (716, N'MURATLI', 59)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (717, N'SARAY', 59)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (718, N'SARKÖY', 59)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (719, N'MARAMARAEREGLISI', 59)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (720, N'ALMUS', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (721, N'ARTOVA', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (722, N'TOKAT MERKEZ', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (723, N'ERBAA', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (724, N'NIKSAR', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (725, N'RESADIYE', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (726, N'TURHAL', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (727, N'ZILE', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (728, N'PAZAR', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (729, N'YESILYURT', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (730, N'BASÇIFTLIK', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (731, N'SULUSARAY', 60)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (732, N'TRABZON MERKEZ', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (733, N'AKÇAABAT', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (734, N'ARAKLI', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (735, N'ARSIN', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (736, N'ÇAYKARA', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (737, N'MAÇKA', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (738, N'OF', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (739, N'SÜRMENE', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (740, N'TONYA', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (741, N'VAKFIKEBIR', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (742, N'YOMRA', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (743, N'BESIKDÜZÜ', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (744, N'SALPAZARI', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (745, N'ÇARSIBASI', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (746, N'DERNEKPAZARI', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (747, N'DÜZKÖY', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (748, N'HAYRAT', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (749, N'KÖPRÜBASI', 61)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (750, N'TUNCELI MERKEZ', 62)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (751, N'ÇEMISGEZEK', 62)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (752, N'HOZAT', 62)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (753, N'MAZGIRT', 62)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (754, N'NAZIMIYE', 62)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (755, N'OVACIK', 62)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (756, N'PERTEK', 62)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (757, N'PÜLÜMÜR', 62)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (758, N'BANAZ', 64)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (759, N'ESME', 64)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (760, N'KARAHALLI', 64)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (761, N'SIVASLI', 64)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (762, N'ULUBEY', 64)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (763, N'USAK MERKEZ', 64)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (764, N'BASKALE', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (765, N'VAN MERKEZ', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (766, N'EDREMIT', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (767, N'ÇATAK', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (768, N'ERCIS', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (769, N'GEVAS', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (770, N'GÜRPINAR', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (771, N'MURADIYE', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (772, N'ÖZALP', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (773, N'BAHÇESARAY', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (774, N'ÇALDIRAN', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (775, N'SARAY', 65)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (776, N'YALOVA MERKEZ', 77)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (777, N'ALTINOVA', 77)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (778, N'ARMUTLU', 77)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (779, N'ÇINARCIK', 77)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (780, N'ÇIFTLIKKÖY', 77)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (781, N'TERMAL', 77)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (782, N'AKDAGMADENI', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (783, N'BOGAZLIYAN', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (784, N'YOZGAT MERKEZ', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (785, N'ÇAYIRALAN', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (786, N'ÇEKEREK', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (787, N'SARIKAYA', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (788, N'SORGUN', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (789, N'SEFAATLI', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (790, N'YERKÖY', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (791, N'KADISEHRI', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (792, N'SARAYKENT', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (793, N'YENIFAKILI', 66)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (794, N'ÇAYCUMA', 67)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (795, N'DEVREK', 67)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (796, N'ZONGULDAK MERKEZ', 67)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (797, N'EREGLI', 67)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (798, N'ALAPLI', 67)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (799, N'GÖKÇEBEY', 67)
GO
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (800, N'ÇANAKKALE MERKEZ', 17)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (801, N'AYVACIK', 17)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (802, N'BAYRAMIÇ', 17)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (803, N'BIGA', 17)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (804, N'BOZCAADA', 17)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (805, N'ÇAN', 17)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (806, N'ECEABAT', 17)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (807, N'EZINE', 17)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (808, N'LAPSEKI', 17)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (809, N'YENICE', 17)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (810, N'ÇANKIRI MERKEZ', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (811, N'ÇERKES', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (812, N'ELDIVAN', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (813, N'ILGAZ', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (814, N'KURSUNLU', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (815, N'ORTA', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (816, N'SABANÖZÜ', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (817, N'YAPRAKLI', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (818, N'ATKARACALAR', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (819, N'KIZILIRMAK', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (820, N'BAYRAMÖREN', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (821, N'KORGUN', 18)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (822, N'ALACA', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (823, N'BAYAT', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (824, N'ÇORUM MERKEZ', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (825, N'IKSIPLI', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (826, N'KARGI', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (827, N'MECITÖZÜ', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (828, N'ORTAKÖY', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (829, N'OSMANCIK', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (830, N'SUNGURLU', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (831, N'DODURGA', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (832, N'LAÇIN', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (833, N'OGUZLAR', 19)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (834, N'ADALAR', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (835, N'BAKIRKÖY', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (836, N'BESIKTAS', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (837, N'BEYKOZ', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (838, N'BEYOGLU', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (839, N'ÇATALCA', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (840, N'EMINÖNÜ', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (841, N'EYÜP', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (842, N'FATIH', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (843, N'GAZIOSMANPASA', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (844, N'KADIKÖY', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (845, N'KARTAL', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (846, N'SARIYER', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (847, N'SILIVRI', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (848, N'SILE', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (849, N'SISLI', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (850, N'ÜSKÜDAR', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (851, N'ZEYTINBURNU', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (852, N'BÜYÜKÇEKMECE', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (853, N'KAGITHANE', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (854, N'KÜÇÜKÇEKMECE', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (855, N'PENDIK', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (856, N'ÜMRANIYE', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (857, N'BAYRAMPASA', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (858, N'AVCILAR', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (859, N'BAGCILAR', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (860, N'BAHÇELIEVLER', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (861, N'GÜNGÖREN', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (862, N'MALTEPE', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (863, N'SULTANBEYLI', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (864, N'TUZLA', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (865, N'ESENLER', 34)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (866, N'ALIAGA', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (867, N'BAYINDIR', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (868, N'BERGAMA', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (869, N'BORNOVA', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (870, N'ÇESME', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (871, N'DIKILI', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (872, N'FOÇA', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (873, N'KARABURUN', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (874, N'KARSIYAKA', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (875, N'KEMALPASA', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (876, N'KINIK', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (877, N'KIRAZ', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (878, N'MENEMEN', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (879, N'ÖDEMIS', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (880, N'SEFERIHISAR', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (881, N'SELÇUK', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (882, N'TIRE', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (883, N'TORBALI', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (884, N'URLA', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (885, N'BEYDAG', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (886, N'BUCA', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (887, N'KONAK', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (888, N'MENDERES', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (889, N'BALÇOVA', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (890, N'ÇIGLI', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (891, N'GAZIEMIR', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (892, N'NARLIDERE', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (893, N'GÜZELBAHÇE', 35)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (894, N'SANLIURFA MERKEZ', 63)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (895, N'AKÇAKALE', 63)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (896, N'BIRECIK', 63)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (897, N'BOZOVA', 63)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (898, N'CEYLANPINAR', 63)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (899, N'HALFETI', 63)
GO
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (900, N'HILVAN', 63)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (901, N'SIVEREK', 63)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (902, N'SURUÇ', 63)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (903, N'VIRANSEHIR', 63)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (904, N'HARRAN', 63)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (905, N'BEYTÜSSEBAP', 73)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (906, N'SIRNAK MERKEZ', 73)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (907, N'CIZRE', 73)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (908, N'IDIL', 73)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (909, N'SILOPI', 73)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (910, N'ULUDERE', 73)
INSERT [dbo].[States] ([Id], [Name], [CityId]) VALUES (911, N'GÜÇLÜKONAK', 73)
SET IDENTITY_INSERT [dbo].[States] OFF
ALTER TABLE [dbo].[States]  WITH CHECK ADD  CONSTRAINT [FK_States_Cities_CityId] FOREIGN KEY([CityId])
REFERENCES [dbo].[Cities] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[States] CHECK CONSTRAINT [FK_States_Cities_CityId]
GO
